// VueFrontend/knowledge-accounting-vue/src/components/shared/Header.vue
<template>
    <header>
        <nav class="navbar navbar-expand-lg">
            <a class="navbar-brand" href="/">Knowledge<br>System</a>
            <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/statistic">Statistic</a>
            </li>
            <li v-if=true class="nav-item">
                <a class="nav-link" href="/register">Sign Up</a>
            </li>
            <li v-if=true class="nav-item">
                <a class="nav-link" href="/login">Sign In</a>
            </li>
            <li v-if=true class="nav-item">
                <a id="logout-link" class="nav-link" href="/">Sign Out</a>
            </li>
            </ul>
            <div class="user-greeting d-flex align-items-center m-0">
            <p class="m-0">Hello, {{userName}}!</p>
            </div>
        </nav>
    </header>
</template>

<script>

export default {
  data () {
    return {
      isAuthorized: true,
      userName: 'Guest'
    }
  }
}

</script>

<style scoped>

.navbar {
  background-color: #255bce;
}

.navbar-brand {
  color: #ffffff;
  font-weight: 900;
  word-wrap: break-word;
}

a {
  color: #f1f1f193;
  font-family: Arial, Helvetica, sans-serif;
}

.nav-link {
  transition: 0.3s;
}

.nav-link:hover {
  color: #ffffff;
}

.user-greeting p {
  font-size: 20px;
  color: #ffffff;
  transition: 0.3s;
}

.user-greeting p:hover {
  color: #d3d3d3;
}

</style>

// KnowledgeAccounting/src/app/components/shared/header/header.component.ts
import { Router } from '@angular/router';
import { UserService } from './../../../services/user/user.service';
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent implements OnInit {


  constructor(private service: UserService, private router: Router) { }

  ngOnInit() {
  }

  get userName() {
    if (this.isAuthorized()) {
      return this.service.getCurrentUserData().UserName;
    }
    return 'Guest';
  }

  isAuthorized(): boolean{
    if (localStorage.getItem('token') !== null) {
      return true;
    }
    return false;
  }

  logout() {
    this.service.logout();
    this.router.navigate(['home']);
  }
}

<header>
  <nav class="navbar navbar-expand-lg">
    <a class="navbar-brand" href="#">Knowledge<br>System</a>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" routerLink="home">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" routerLink="statistic">Statistic</a>
      </li>
      <li *ngIf="!isAuthorized()" class="nav-item">
        <a class="nav-link" href="register">Sign Up</a>
      </li>
      <li *ngIf="!isAuthorized()" class="nav-item">
        <a class="nav-link" routerLink="login">Sign In</a>
      </li>
      <li *ngIf="isAuthorized()" class="nav-item">
        <a id="logout-link" class="nav-link" (click)="logout()">Sign Out</a>
      </li>
    </ul>
    <div class="user-greeting d-flex align-items-center m-0">
      <p class="m-0">Hello, {{userName}}!</p>
    </div>
  </nav>
</header>
